# 全局错误捕获

## 前端

1. 可疑区域增加 try...catch
2. 全局监控JS异常： window.onerror
3. 全局监控静态资源异常： window.addEventListener（‘error’， **true**）
4. 全局捕获没有 catch 的 promise 异常：window.addEventListener（‘unhandledrejection’）
5. iframe 异常：window.onerror
6. VUE errorHandler 和 React componentDidCatch
7. 监控网页崩溃：window 对象的 load 和 beforeunload 配合localstorage
8. Script Error跨域 crossOrigin 解决

## 浏览器

1. window.onerror = function (message, source, lineno, colno, error){}
    不能显示其他域错误具体信息 需要允许跨域

    - `Access-Control-Allow-Origin: *`

    - `<script crossorigin src=""></script>`
    捕获不到语法 及 资源加载错误（接口/静态资源）

2. 给所有的函数添加try catch， 利用ast （uglifyJs）

    只能捕获到同步的运行时错误，对于语法和异步错误无能为力

3. window.addEventListener('error', (error) => {}， **true**) 事件捕获

    加载资源失败的元素会触发一个Event接口的error事件，并执行该元素上的onerror处理函数。这些error事件不会向上冒泡到window， 不过（至少在 Chrome 中）能被单一的window.addEventListener 捕获

    由于网络请求异常不会事件冒泡，因此必须在捕获阶段将其捕捉到才行，但是这种方式虽然可以捕捉到网络请求的异常，但是无法判断 HTTP 的状态是 404 还是其他比如 500 等等，所以还需要配合服务端日志才进行排查分析才可以。

4. window.addEventListener('unhandledrejection')

    全局捕获 Promise 的异常， 可以不单独写catch

5. 崩溃或卡顿， 不能上报

    利用 window 对象的 load 和 beforeunload 事件实现了网页崩溃的监控。

    正常退出设置flag为正常退出状态， 崩溃不会beforeunload， 检查flag

    利用service worker

6. 新的ReportingObserver API

    `const reportingObserver=new ReportingObserver(callback, options?)`

### crossOrigin

`crossOrigin="anonymous"` 不携带 cookie，`crossOrigin="use-credentials"`, 会携带 cookie 和客户端证书等票据

## Vue

vue.config.errorHandler = () => {} 全局

## React

ErrorBoundary 组建，配合componentDidCatch 声明周期

## Nodejs

错误异常有两种场景的出现，一种是代码运行中throw new error没有被捕获，另一种是Promise的失败回调函数，没有对应的reject回调函数处理，针对这两种情况Nodejs都有默认的统一处理方式，就是给整个进程process对象监听相应的错误事件。

```js
process.on('uncaughtException',function(err){}) //监听未捕获的异常
process.on('unhandledRejection',function(err){}) //监听Promise未捕获的异常
```

## Express

`app.use((err, req, res, next) => {})`
